openapi: 3.0.1
info:
  title: Rocket Game API
  version: v1
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /api/parts:
    get:
      tags:
      - part-controller
      operationId: getAllParts
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PartDTO'
    post:
      tags:
      - part-controller
      operationId: createPart
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PartDTO'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/PartDTO'
  /api/chassis:
    post:
      tags:
      - chassis-controller
      operationId: createChassis
      requestBody:
        content:
          application/json:
            schema:
              type: string
              enum:
              - LIGHT
              - MEDIUM
              - HEAVY
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Chassis'
components:
  schemas:
    PartDTO:
      required:
      - description
      - fuel
      - name
      - shield
      - speed
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          maxLength: 30
          minLength: 3
          type: string
        description:
          maxLength: 200
          minLength: 3
          type: string
        partType:
          type: string
        speed:
          type: integer
          format: int32
        shield:
          type: integer
          format: int32
        fuel:
          type: integer
          format: int32
    PartCone:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        rocket:
          type: string
        partType:
          type: string
          enum:
          - PART_CONE
          - PART_ONE
          - PART_TWO
        speed:
          type: integer
          format: int32
        shield:
          type: integer
          format: int32
        fuel:
          type: integer
          format: int32
    Chassis:
      type: object
      properties:
        speed:
          type: integer
          format: int32
        shield:
          type: integer
          format: int32
        fuel:
          type: integer
          format: int32
